root = "."
testdata_dir = "testdata"
tmp_dir = "./cmd/duller/tmp"

[build]
  args_bin = []
  bin = "./cmd/duller/tmp/main"
  cmd = "npx tailwindcss -i ./static/css/main.css -o ./static/css/tw.css -c ./tailwind.config.js && templ generate && go build -o ./cmd/duller/tmp/main ./cmd/duller/main.go"
  post_cmd = ["pkill main"]
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["tmpl", "internal", "cmd/duller", "static", ]
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
